CREATE TABLE IF NOT EXISTS users(
                                    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    email varchar(255),
                                    login varchar(255),
                                    name varchar(255),
                                    birthday Date);

CREATE TABLE IF NOT EXISTS mpa(
                                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name varchar(5));

CREATE TABLE IF NOT EXISTS films(
                                    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(100),
                                    description varchar(200),
                                    release_date Date,
                                    duration INT,
                                    mpa INT,
                                    FOREIGN KEY (mpa) REFERENCES mpa(id));


CREATE TABLE IF NOT EXISTS genres(
                                     genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(15));

CREATE TABLE IF NOT EXISTS film_genre(
                                         film_id INT,
                                         genre_id INT,
                                         FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
                                         FOREIGN KEY (genre_id) REFERENCES genres(genre_id));

CREATE TABLE IF NOT EXISTS friends(
                                      friendship_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id INT,
                                      friend_id INT,
                                      status BOOLEAN,
                                      FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                                      FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS likes(
                                    likes_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id INT,
                                    film_id INT,
                                    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                                    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE);